[project]
name = "mylogger"
version = "0.1.4"
authors = [{ name = "Sven Upgang" }]
description = "A wrapper for python logging to be reused in private projects"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = []
